server/routes/judge.py
import io
import json
import datetime
from flask import redirect, abort, render_template, request, session, send_file, Blueprint, current_app as app
from server.data import Contest, ScoreboardTeamProblem, Balloon, verdict_explanation
from lib.models import Submission, SubmissionQueue, Balloon as BalloonModel
from server.util import judge_only, judge_is_logged_in, url_for

judge = Blueprint("judge", __name__, template_folder="../templates")

# judge.context_processor(context_processor)


@judge.route('/')
@judge_only
def index():
    return render_template('judge/index.html')


@judge.route('/login/', methods={'GET', 'POST'})
def login():
    goto = request.args.get('next', url_for('judge.index'))
    judge_name = ''
    bad_login = False
    if judge_is_logged_in():
        return redirect(goto)
    if request.method == 'POST':
        # TODO: make sure 'team' and 'password' are in request.form
        judge_name = request.form['judge']
        password = request.form['password']
        if judge_name in app.contest.judges and app.contest.judges[judge_name].password == password:
            session['judge'] = judge_name
            return redirect(goto)
        else:
            session.pop('judge', '')
            bad_login = True
    return render_template('judge/login.html', judge_name=judge_name, bad_login=bad_login)


@judge.route('/logout/')
@judge_only
def logout():
    session.pop('judge', '')
    return redirect(url_for('judge.login'))


@judge.route('/reload/')
@judge_only
def reload():
    app.contest = Contest.load(app.opts.contest)
    return redirect(url_for('judge.index'))


@judge.route('/scoreboard/', defaults={'opts': ''})
@judge.route('/scoreboard/<opts>/')
def view_scoreboard(opts):
    phase = app.contest.get_current_phase()
    if not phase.scoreboard_problems:
        abort(404)

    opts = {s.split('=', 1)[0]: (s.split('=', 1)[1] if '=' in s else True) for s in opts.split(',')}
    opts['groups'] = set(opts.get('groups', '+'.join(app.contest.groups.keys())).split('+'))

    cur_time = datetime.datetime.now()
    subs = Submission.query.filter(Submission.submitted <= cur_time).filter(Submission.problem.in_(phase.scoreboard_problems)).order_by(Submission.submitted).all()
    sb = {team: {problem: ScoreboardTeamProblem() for problem in phase.scoreboard_problems} for team, v in app.contest.teams.items() if len(v.groups & opts['groups']) > 0}

    for sub in subs:
        if sub.problem not in phase.scoreboard_problems:
            continue

        if sub.team not in sb:
            continue

        cur = sb[sub.team][sub.problem]

        if sub.verdict == 'QU':
            cur.submit_new()
        elif sub.verdict not in {'SE', 'RF', 'CJ', 'CE'}:
            cur.submit((sub.submitted - app.contest.start).total_seconds(), sub.verdict == 'AC')

    ssb = sorted((-sum(sb[team][problem].is_solved() for problem in phase.scoreboard_problems),
                  sum(sb[team][problem].time_penalty() for problem in phase.scoreboard_problems),
                  team) for team in sb.keys())

    sb = [(s[2], -s[0], s[1], sb[s[2]]) for s in ssb]

    return render_template('judge/scoreboard.html', scoreboard=sb)


@judge.route('/submissions/', defaults={'team_name': None})
@judge.route('/submissions/<team_name>/')
@judge_only
def list_submissions(team_name):
    cur_time = datetime.datetime.now()
    submissions = Submission.query
    if team_name is not None:
        submissions = submissions.filter_by(team=team_name)

    submissions = submissions.filter(Submission.submitted <= cur_time).order_by(Submission.submitted).all()

    def format_verdict_classes(vs):
        vs = set(vs.split('+'))
        if vs <= {'QU'}:
            return 'info'
        if vs <= {'AC'}:
            return 'success'
        if vs <= {'SE', 'RF', 'CJ', 'CE'}:
            return 'warning'
        if vs <= {'PE', 'WA', 'RE', 'TL', 'ML', 'OL'}:
            return 'danger'
        return ''

    label_class = {
        'QU': 'info',
        'AC': 'success',
        'PE': 'warning',
        'WA': 'danger',
        'CE': 'warning',
        'RE': 'danger',
        'TL': 'danger',
        'ML': 'danger',
        'OL': 'danger',
        'SE': 'default',
        'RF': 'default',
        'CJ': 'default',
    }

    def label_class_for(v):
        return "label label-" + label_class.get(v, 'default')

    return render_template('judge/submissions.html',
                           submissions=reversed(submissions),
                           format_verdict_classes=format_verdict_classes,
                           label_class_for=label_class_for,
                           )


@judge.route('/submission/<int:sub_id>/', methods={'GET', 'POST'})
@judge_only
def view_submission(sub_id):
    sub = Submission.query.filter_by(id=sub_id).first()
    if not sub:
        abort(404)

    if request.method == 'POST':
        if 'verdict' in request.form and 'judge_response' in request.form:
            v = request.form['verdict'].split('+')
            if not (len(v) == len(set(v)) and set(v) <= set(verdict_explanation.keys())):
                abort(400)

            sub.verdict = request.form['verdict']
            sub.judge_response = request.form['judge_response']

            if sub.verdict == 'QU':
                qsub = SubmissionQueue.query.filter_by(submission_id=sub.id).first()
                if qsub:
                    qsub.dequeued_at = None
                else:
                    app.db.session.add(SubmissionQueue(sub.id))

            app.db.session.commit()
            return redirect(url_for('judge.view_submission', sub_id=sub_id))
        else:
            abort(400)

    return render_template('judge/submission.html', submission=sub)


@judge.route('/teams/')
@judge_only
def list_teams():
    return render_template('judge/teams.html',
                           teams=sorted(app.contest.teams.values(), key=lambda team: team.title)
                           )


@judge.route('/balloons/', defaults={'id': None})
@judge.route('/balloons/deliver/<int:id>/')
@judge_only
def balloons(id):
    if id is not None:
        balloon = BalloonModel.query.filter_by(balloon_id=id).first()
        if balloon:
            balloon.delivered = True
            app.db.session.commit()
        return redirect(url_for('judge.balloons'))

    submissions = {sub.id: sub for sub in Submission.query.all()}
    dballoons = BalloonModel.query.all()
    balloons = []
    for balloon in dballoons:
        sub = submissions[balloon.submission_id]
        team = app.contest.teams[sub.team]
        problem = app.contest.problems[sub.problem]
        balloons.append(Balloon(balloon.balloon_id, sub, team, problem, balloon.delivered))

    return render_template('judge/balloons.html',
                           balloons=sorted(balloons, key=lambda balloon: balloon.submission.submitted)
                           )


@judge.route('/resolver/')
@judge_only
def resolver():
    return render_template('judge/resolver.html')


@judge.route('/export/', defaults={'no': None})
@judge.route('/export/generate/<int:no>/')
@judge_only
def export(no):
    if no is not None:

        if no == 1:
            # out = io.StringIO()
            out = io.BytesIO()

            out.write(('''<?xml version="1.0" encoding="UTF-8"?>
    <contest>
        <info>
            <length>%(duration)s</length>
            <penalty>20</penalty>
            <started>True</started>
            <title>%(title)s</title>
        </info>
    ''' % {
                'duration': '%02d:%02d:%02d' % (app.contest.duration // 60, app.contest.duration % 60, 0),
                'title': app.contest.title,
            }).encode('utf-8'))

            teams = {}
            problems = {}

            for name, team in app.contest.teams.items():
                teams[name] = len(teams) + 1

            for name in app.contest.phases[-1][1].scoreboard_problems:
                problems[name] = len(problems) + 1

            for name, id in problems.items():
                out.write(('''
        <problem>
            <id>%(id)d</id>
            <name>%(name)s</name>
        </problem>''' % {'id': id, 'name': name}).encode('utf-8'))

            for name, id in teams.items():
                out.write(('''
        <team>
            <id>%(id)d</id>
            <name>%(name)s</name>
        </team>''' % {'id': id, 'name': app.contest.teams[name].title}).encode('utf-8'))

            subs = Submission.query.filter(Submission.verdict != 'QU').all()
            for no, sub in enumerate(sorted(subs, key=lambda sub: sub.submitted)):
                out.write(('''
        <run>
            <id>%(no)d</id>
            <judged>False</judged>
            <problem>%(problem_id)d</problem>
            <status>fresh</status>
            <team>%(team_id)d</team>
            <time>%(time)f</time>
        </run>
        <run>
            <id>%(no)d</id>
            <judged>True</judged>
            <penalty>%(penalty)s</penalty>
            <problem>%(problem_id)d</problem>
            <result>%(verdict)s</result>
            <solved>%(solved)s</solved>
            <status>done</status>
            <team>%(team_id)d</team>
            <time>%(time)f</time>
        </run>
    ''' % {
                    'no': no + 1,
                    'penalty': 'True' if set(sub.verdict.split('+')) <= {'RE', 'TL', 'ML', 'WA', 'PE'} else 'False',
                    'problem_id': problems[sub.problem],
                    'verdict': sub.verdict,
                    'solved': 'True' if sub.verdict == 'AC' else 'False',
                    'team_id': teams[sub.team],
                    'time': (sub.submitted - app.contest.start).total_seconds(),
                }).encode('utf-8'))

            out.write(('''
    </contest>
    ''').encode('utf-8'))

            out.seek(0)
            return send_file(out,
                             attachment_filename=app.contest.id + '_resolver.xml',
                             as_attachment=True,

server/templates/judge/export.html
{% extends "judge/main.html" %}
{% block title %}
{{ contest.title }} - export
{% endblock %}
{% block content %}

<h3>Data for Resolver</h3>
<p>Here you can find generated data for the <a href="https://github.com/icpc-live/graphics">ICPC Live Resolver</a>.</p>

<h5><a href="{{ url_for('judge.export', no=1) }}">Resolver data (XML)</a></h5>
<h5><a href="{{ url_for('judge.export', no=3) }}">Resolver data (JSON)</a></h5>

{% endblock %}

server/templates/judge/main.html
{% extends "judge/base.html" %}
{% block body %}

<div class="navbar navbar-default navbar-fixed-top" id="header">
    <div class="navbar-inner">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('judge.index') }}">{{ contest.title }}</a>
                {% if phase.status %}
                    <p class="navbar-text">{{ phase.status }}</p>
                {% endif %}
                {% if phase.countdown != None and phase.current_countdown() >= 0 %}
                    <p class="navbar-text countdown">{{ phase.current_countdown() | format_time }}</p>
                {% endif %}
            </div>
            <div class="collapse navbar-collapse" id="topbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ judge.name }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('judge.logout') }}"><i class="fa fa-user-times"></i> Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper">
    <div class="sidebar-wrapper">
        <ul class="nav sidebar nav-stacked problem-list">
            {% if phase.scoreboard_problems %}
                <li><a href="{{ url_for('judge.view_scoreboard') }}"><i class="fa fa-flag"></i> Scoreboard</a></li>
            {% endif %}

            <li><a href="{{ url_for('judge.list_submissions') }}"><i class="fa fa-check-square-o"></i> Submissions</a></i>
            <li><a href="{{ url_for('judge.list_teams') }}"><i class="fa fa-group"></i> Teams</a></i>
            <li><a href="{{ url_for('judge.balloons') }}"><i class="fa fa-thumbs-up"></i> Balloons</a></i>
            <li><a href="{{ url_for('judge.export') }}"><i class="fa fa-download"></i> Export</a></i>
            <li><a href="{{ url_for('judge.resolver') }}"><i class="fa fa-video-camera"></i> Resolver</a></i>
            <li><a href="{{ url_for('judge.reload') }}"><i class="fa fa-cogs"></i> Reload Config</a></i>
        </ul>
    </div>
    <div class="content-wrapper">
        <div class="container-fluid" id="main">
            <div class="row">
                <div class="col-xs-12 content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 footer">
            <hr />
            generated in {{ "%.04f" % (g.request_time() * 1000.0) }}ms by <span class="epsilon" title="epsilon">&epsilon;</span>
        </div>
    </div>

</div>
{% endblock %}

server/templates/judge/resolver.html
{% extends "base.html" %}
{% block title %}
{{ contest.title }} - resolver
{% endblock %}
{% block body %}

<style type="text/css">
.scoreboard tr { background: white; }
.scoreboard thead th.problem { width: 80px; }
</style>

<div id="content">

    <table class="table table-bordered scoreboard" id="scoreboard">
        <thead>
            <tr>
                <th>#</th>
                <th>Team</th>
                <th>Points</th>
                <th>Penalty</th>
                {#
                {% for i, problem in enumerate(phase.scoreboard_problems) %}
                    # <th>{{ contest.problems[problem].title }}</th> #
                    <th title="{{ contest.problems[problem].title }}">{{ i+1 }}</th>
                {% endfor %}
                #}
            </tr>
        </thead>
        <tbody>
            {#
            {% for i, (team, points, penalty, sb) in enumerate(scoreboard) %}
                <tr>
                    <td>
                        {% if points > 0 %}
                            {{ i+1 }}
                        {% endif %}
                    </td>
                    <td>{{ contest.teams[team].title }}</td>
                    <td>{{ points }}</td>
                    <td>{{ penalty | format_time }}</td>
                    {% for p in phase.scoreboard_problems %}
                        {% set problem = sb[p] %}

                        {% if problem.solved_at != None %}
                            <td class="ac">
                        {% elif problem.new_submissions > 0 %}
                            <td class="new">
                        {% elif problem.try_count > 0 %}
                            <td class="wa">
                        {% else %}
                            <td>
                        {% endif %}

                            {% if problem.solved_at == None %}
                            --:--
                            {% else %}
                                {{ problem.solved_at | format_time }}
                            {% endif %}

                            {% if problem.try_count > 0 or problem.new_submissions > 0 %}
                            ({{ problem.try_count }}{% if problem.new_submissions > 0 %}+{{ problem.new_submissions }}{% endif %})
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            #}
        </tbody>
    </table>

</div>

{% endblock %}
{% block below %}
<script type="text/javascript">

jQuery(function ($) {
    var TIME_MULTIPLIER = 200;
    var SUBMISSION_PENALTY = 20;
    var ROW_ANIMATE_TIME = 1000;

    var format_time = function (t) {
        var ten = function (x)  {
            return (x < 10 ? '0' : '') + x;
        };

        return ten(Math.floor(t/60)) + ':' + ten(Math.floor(t)%60);
    };

    function Team(team, problems) {

        var row = $("<tr></tr>");
        var no_cell = $("<td></td>");
        var title_cell = $("<td></td>").text(team['name']);
        var points_cell = $("<td></td>").text('0');
        var penalty_cell = $("<td></td>").text('00:00');

        row.append(no_cell)
           .append(title_cell)
           .append(points_cell)
           .append(penalty_cell);

        var ps = {};
        for (var i = 0; i < problems.length; i++) {
            var problem_id = problems[i]['id'];

            var problem_cell = $('<td></td>');

            ps[problem_id] = {
                cell: problem_cell,
                tried: false,
                solved: false,
                tries: 0,
            };

            row.append(problem_cell);
        }

        return {
            id: team['id'],
            name: team['name'],
            row: row,
            cur_row: row,
            no_cell: no_cell,
            title_cell: title_cell,
            points_cell: points_cell,
            penalty_cell: penalty_cell,
            problems: ps,
            penalty: 0.0,
            points: 0,

            handle_submission: function (sub) {
                var problem_id = sub['problem_id'];
                var verdict = sub['verdict'];
                var time = sub['time'];
                var problem = this.problems[problem_id];
                var solved = verdict == 'AC';

                if (problem.solved) return;
                if (verdict == 'CE') return;

                problem.tried = true;
                if (solved) {
                    this.penalty += time + SUBMISSION_PENALTY * 60 * problem.tries;
                    this.points += 1;
                    problem.solved = true;
                    problem.solved_at = time;

                    problem.cell.removeClass('wa');
                    problem.cell.addClass('ac');
                    problem.cell.effect('highlight', { 'color': 'green' }, 2000);
                } else {
                    problem.tries += 1;

                    if (problem.tries == 1) {
                        problem.cell.addClass('wa');
                        problem.cell.effect('highlight', { 'color': 'red' }, 2000);
                    }
                }

                var txt = '';
                if (!problem.solved) {
                    txt += '--:--';
                } else {
                    txt += format_time(problem.solved_at);
                }
                if (problem.tries > 0) {
                    txt += ' (' + problem.tries + ')';
                }
                problem.cell.text(txt);

                this.points_cell.text(this.points);
                this.penalty_cell.text(format_time(this.penalty));

                if (this.points > 0) {
                    this.no_cell.text(this.no);
                }
            },
        };
    };

    var row_animate = function (team, standings, row, no, callback) {
        var at = row.offset();
        var height = row.height();
        var width = row.width();
        var widths = [];
        for (var i = 0; i < row[0].children.length; i++) {
            widths.push($(row[0].children[i]).width());
        }

        var fill_up = $('<tr></tr>');
        fill_up.css('visibility', 'hidden');
        fill_up.height(0);
        fill_up.width(width);

        // for (var i = 0; i < row[0].children.length; i++) {
        //     // var cell = $(clone[0].children[i]);
        //     // cell.width($(row[0].children[i]).width());
        //     // cell.height($(row[0].children[i]).height());
        //     // $(fill2[0].children[i]).width($(row[0].children[i]).width());
        //     // $(fill2[0].children[i]).empty();
        //     // $(fill2[0].children[i]).css('padding-top', '0');
        //     // $(fill2[0].children[i]).css('padding-bottom', '0');
        //     // $(fill2[0].children[i]).height(0);
        // }

        var fill_down = $('<tr></tr>');
        row.replaceWith(fill_down);
        team.cur_row = fill_down;
        fill_down.css('visibility', 'hidden');
        fill_down.height(height);
        fill_down.width(width);

        row.height(height);
        row.width(width);
        for (var i = 0; i < row[0].children.length; i++) {
            $(row[0].children[i]).width(widths[i]);
        }

        var div = $('<div></div>');
        div.append($('<table></table>')
                    .addClass('table table-bordered scoreboard')
                    .append('<tbody></tbody>')
                    .append(row))
           .width(width)
           .height(height)
           .css('position', 'absolute')
           .css('top', at.top + 'px')
           .css('left', (at.left+1) + 'px')
           .appendTo($('#content'));

        if (no == 0) {
            $('#scoreboard tbody').prepend(fill_up);
        } else {
            fill_up.insertAfter(standings[no - 1].cur_row);
        }

        team.cur_row = fill_up;

        fill_down.animate({
            'height': '0'
        }, ROW_ANIMATE_TIME);

        fill_up.animate({
            'height': height
        }, ROW_ANIMATE_TIME);

        div.animate({
            'top': fill_up.offset().top + 'px'
        }, ROW_ANIMATE_TIME, function () {

            row.width('auto').height('auto');
            for (var i = 0; i < row[0].children.length; i++) {
                $(row[0].children[i]).width('auto');
            }

            fill_up.replaceWith(row);
            team.cur_row = row;
            div.remove();
            fill_down.remove();
            callback();
        });
    };

    var cmp = function(a, b) { return a < b ? -1 : a > b ? 1 : 0; };
    var update_standings = function(standings, animate, callback) {

        standings.sort(function (a, b) {
            if (a.points != b.points) return -cmp(a.points, b.points);
            if (Math.abs(a.penalty - b.penalty) > 1e-9) return cmp(a.penalty, b.penalty);
            if (a.name != b.name) return cmp(a.name, b.name);
            return 0;
        });

        // $('#scoreboard tbody tr').detach();

        var row_at = 0;
        var next_row = function() {
            if (row_at == standings.length) {
                callback();
            } else {
                var old_no = standings[row_at].no;
                standings[row_at].no = row_at + 1;
                if (standings[row_at].points > 0) {
                    standings[row_at].no_cell.text(row_at + 1);
                } else {
                    standings[row_at].no_cell.text('');
                }
                if (standings[row_at].no < old_no) {
                    if (animate) {

                        row_animate(standings[row_at], standings, standings[row_at].row, standings[row_at].no - 1, function () {
                            row_at += 1;
                            next_row();
                        });

                    } else {
                        standings[row_at].row.detach();

                        if (standings[row_at].no == 1) {
                            $('#scoreboard tbody').prepend(standings[row_at].row);
                        } else {
                            standings[row_at].row.insertAfter(document.getElementById('scoreboard').children[1].children[standings[row_at].no - 2]);
                        }

                        row_at += 1;
                        next_row();
                    }

                } else {
                    row_at += 1;
                    next_row();
                }
            }
        };

        next_row();
    };

    var json_url = "{{ url_for('judge.export', no=3) }}";
    $.getJSON(json_url, function (data) {

        var info = data['info'];
        SUBMISSION_PENALTY = info['penalty'];

        var problems = data['problems'];
        var subs = data['runs'];

        for (var i = 0; i < problems.length; i++) {
            var id = problems[i]['id'];
            var title = problems[i]['name'];
            $('#scoreboard thead tr').append($('<th></th>').addClass('problem').attr('title', title).text(id));
        }

        var teams = {};
        var standings = [];
        for (var i = 0; i < data['teams'].length; i++) {
            var team = new Team(data['teams'][i], problems);
            teams[team.id] = team;

            team.no = i + 1;
            $('#scoreboard tbody').append(team.row);
            standings.push(team);
        }

        subs.sort(function (a, b) {
            return a.time - b.time;
        });

        var process_sub = function (sub_at) {

                var sub = subs[sub_at];
                var team = teams[sub['team_id']];
                console.log(sub);
                team.handle_submission(sub);
                update_standings(standings, true, function () {
                    if (sub_at + 1 < subs.length) {
                        setTimeout(function () {
                            process_sub(sub_at + 1);
                        }, (subs[sub_at + 1]['time'] - subs[sub_at]['time']) / TIME_MULTIPLIER * 1000);
                    }
                });
            };


        update_standings(standings, false, function () {
            if (subs.length > 0) {
                setTimeout(function () {
                    process_sub(0);
                }, subs[0]['time'] /  TIME_MULTIPLIER * 1000);
            }
        });

        // for (var i = 0; i < subs.length; i++) {
        //     setTimeout(function (j) {
        //         return function () {
        //             process_sub(j);
        //         };
        //     }(i), subs[i]['time'] / TIME_MULTIPLIER * 1000);
        // }

    });
});

</script>
{% endblock %}

server/templates/judge/scoreboard.html
{% extends "judge/main.html" %}
{% block title %}
{{ contest.title }} - scoreboard
{% endblock %}
{% block content %}

{% if phase.frozen != None and contest.time_elapsed() >= 60.0 * phase.frozen %}
    <h4>The scoreboard has been frozen</h4>
    <h5>The below judge scoreboard is not frozen</h5>
{% endif %}

<div class="btn-group" style="margin-bottom:10px">
    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Groups
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        {% for title, group in sorted(map(reversed, contest.groups.items())) %}
            <li><a href="{{ url_for('judge.view_scoreboard', opts='groups=' + group) }}">{{ title }}</a></li>
        {% endfor %}
    </ul>
</div>

<table class="table table-bordered table-striped scoreboard">
    <tr>
        <th>#</th>
        <th>Team</th>
        <th>Points</th>
        <th>Penalty</th>
        {% for i, problem in enumerate(phase.scoreboard_problems) %}
            {# <th>{{ contest.problems[problem].title }}</th> #}
            <th title="{{ contest.problems[problem].title }}">{{ i+1 }}</th>
        {% endfor %}
    </tr>
    {% for i, (team, points, penalty, sb) in enumerate(scoreboard) %}
        <tr>
            <td>
                {% if points > 0 %}
                    {{ i+1 }}
                {% endif %}
            </td>
            <td>{{ contest.teams[team].title }}</td>
            <td>{{ points }}</td>
            <td>{{ penalty | format_time }}</td>
            {% for p in phase.scoreboard_problems %}
                {% set problem = sb[p] %}

                {% if problem.solved_at != None %}
                    <td class="ac">
                {% elif problem.new_submissions > 0 %}
                    <td class="new">
                {% elif problem.try_count > 0 %}
                    <td class="wa">
                {% else %}
                    <td>
                {% endif %}

                    {% if problem.solved_at == None %}
                       --:--
                    {% else %}
                        {{ problem.solved_at | format_time }}
                    {% endif %}

                    {% if problem.try_count > 0 or problem.new_submissions > 0 %}
                    ({{ problem.try_count }}{% if problem.new_submissions > 0 %}+{{ problem.new_submissions }}{% endif %})
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

{% endblock %}

server/templates/judge/submissions.html
{% extends "judge/main.html" %}
{% block title %}
{{ contest.title }} - submissions
{% endblock %}
{% block content %}

    <div class="btn-group" style="margin-bottom:10px">
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Teams
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
                <li><a href="{{ url_for('judge.list_submissions') }}">All</a></li>
                <li class="divider"></li>
            {% for name, team in sorted(contest.teams.items()) %}
                <li><a title="{{ name }}" href="{{ url_for('judge.list_submissions', team_name=name) }}">{{ team.title }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <table class="table table-condensed submissions">
        <tr>
            <th class="sub_id">ID</th>
            <th class="sub_submitted">Submitted</th>
            <th class="sub_team">Team</th>
            <th class="sub_problem">Problem</th>
            <th class="sub_language">Language</th>
            <th class="sub_verdict">Verdict</th>
            <th class="sub_time">Time</th>
            <th class="sub_memory">Memory</th>
        </tr>
        {% for sub in submissions %}
            <tr class="row-success {{ format_verdict_classes(sub.verdict) }}">
                <td class="sub_id"><a href="{{ url_for('judge.view_submission', sub_id=sub.id) }}">{{ sub.id }}</a></td>
                <td class="sub_submitted">{{ sub.submitted | format_time }}</td>
                <td class="sub_team">{{ sub.team }}</td>
                <td class="sub_problem"><a href="{{ url_for('default.view_problem', problem_id=sub.problem) }}">{{ contest.problems[sub.problem].title | safe }}</a></td>
                <td class="sub_language">{{ sub.language }}</td>
                <td class="sub_verdict">
                    {% for verdict in sub.verdict.split('+') %}
                        <span class="{{ label_class_for(verdict) }}" title="{{ verdict_explanation.get(verdict, verdict) }}">{{ verdict }}</span>
                    {% endfor %}
                </td>
                <td class="sub_time">{{ '' if sub.time == None else '%d ms' % sub.time }}</td>
                <td class="sub_memory">{{ '' if sub.memory == None else '%d KB' % sub.memory }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

server/templates/judge/teams.html
{% extends "judge/main.html" %}
{% block title %}
{{ contest.title }} - teams
{% endblock %}
{% block content %}

<ul class="media-list">
    {% for team in teams %}
    <li class="media">
        <div class="media-body">
            <h4 class="media-heading">{{ team.title }}</h4>
            <div>Username: {{ team.name }}</div>
            <div>Location: {{ team.location }}</div>
            <div>Groups: {{ ', '.join(team.groups) }}</div>
            <div><a href="{{ url_for('judge.list_submissions', team_name=team.name) }}">Submissions</a></div>
            <hr />
        </div>
    </li>
    {% endfor %}
</ul>

{% endblock %}