server/routes/default.py
import re
import os
import datetime
import lib.text as text
from flask import redirect, abort, render_template, request, session, send_from_directory, Blueprint, current_app as app
from server.data import ScoreboardTeamProblem, Contest
from lib.models import Submission, SubmissionQueue
from server.util import url_for, get_team, is_logged_in, login_required

default = Blueprint("default", __name__, template_folder="../templates")

# default.context_processor(context_processor)


@default.route('/scoreboard/', defaults={'opts': ''})
@default.route('/scoreboard/<opts>/')
def view_scoreboard(opts):
    phase = app.contest.get_current_phase()
    if not phase.scoreboard_problems:
        abort(404)
    opts = {s.split('=', 1)[0]: (s.split('=', 1)[1] if '=' in s else True) for s in opts.split(',')}
    opts['groups'] = set(opts.get('groups', '+'.join(app.contest.groups.keys())).split('+'))

    cur_time = datetime.datetime.now()
    subs = Submission.query.filter(Submission.submitted <= cur_time).filter(Submission.problem.in_(phase.scoreboard_problems)).order_by(Submission.submitted).all()
    sb = {team: {problem: ScoreboardTeamProblem() for problem in phase.scoreboard_problems} for team, v in app.contest.teams.items() if len(v.groups & opts['groups']) > 0}

    for sub in subs:
        if sub.problem not in phase.scoreboard_problems:
            continue

        if sub.team not in sb:
            continue

        cur = sb[sub.team][sub.problem]

        if (phase.frozen is not None and sub.submitted >= app.contest.second_format(60.0 * phase.frozen) and (not is_logged_in() or get_team().name != sub.team)) or sub.verdict == 'QU':
            cur.submit_new()
        elif sub.verdict not in {'SE', 'RF', 'CJ', 'CE'}:
            cur.submit((sub.submitted - app.contest.start).total_seconds(), sub.verdict == 'AC')

    ssb = sorted((-sum(sb[team][problem].is_solved() for problem in phase.scoreboard_problems),
                  sum(sb[team][problem].time_penalty() for problem in phase.scoreboard_problems),
                  team) for team in sb.keys())

    sb = [(s[2], -s[0], s[1], sb[s[2]]) for s in ssb]

    if opts.get('full', False):
        return render_template('scoreboard_full.html', scoreboard=sb)
    else:
        return render_template('scoreboard.html', scoreboard=sb)


@default.route('/submissions/')
@login_required
def list_submissions():
    team = get_team()
    cur_time = datetime.datetime.now()
    submissions = Submission.query.filter_by(team=team.name).filter(Submission.submitted <= cur_time).order_by(Submission.submitted).all()

    def format_verdict_classes(vs):
        vs = set(vs.split('+'))
        if vs <= {'QU'}:
            return 'info'
        if vs <= {'AC'}:
            return 'success'
        if vs <= {'SE', 'RF', 'CJ', 'CE'}:
            return 'warning'
        if vs <= {'PE', 'WA', 'RE', 'TL', 'ML', 'OL'}:
            return 'danger'
        return ''

    label_class = {
        'QU': 'info',
        'AC': 'success',
        'PE': 'warning',
        'WA': 'danger',
        'CE': 'warning',
        'RE': 'danger',
        'TL': 'danger',
        'ML': 'danger',
        'OL': 'danger',
        'SE': 'default',
        'RF': 'default',
        'CJ': 'default',
    }

    def label_class_for(v):
        return "label label-" + label_class.get(v, 'default')

    return render_template('submissions.html',
                           submissions=reversed(submissions),
                           format_verdict_classes=format_verdict_classes,
                           label_class_for=label_class_for
                           )


@default.route('/submission/<int:sub_id>/')
@login_required
def view_submission(sub_id):
    team = get_team()
    sub = Submission.query.filter_by(id=sub_id).first()
    if not sub or sub.team != team.name:
        abort(404)
    return render_template('submission.html', submission=sub)


@default.route('/problem/<problem_id>/', methods={'GET', 'POST'}, defaults={"sub_id": None})
@default.route('/problem/<problem_id>/<int:sub_id>', methods={'GET', 'POST'})
def view_problem(problem_id, sub_id):

    problem = app.contest.problems.get(problem_id)
    phase = app.contest.get_current_phase()
    if not problem:
        abort(404)
    if request.method == 'POST':

        if problem_id not in phase.submit_problems:
            abort(404)

        if not is_logged_in():
            return redirect(url_for('default.login', next=request.path))

        team = get_team()
        if (
                'language' in request.form and
                ('source_file' in request.files or 'source_code' in request.form) and
                request.form['language'] in app.contest.languages):

            if 'source_file' in request.files:
                code = request.files['source_file'].read()
                try:
                    code = code.decode('utf-8')
                except UnicodeDecodeError:
                    code = text.bytes2unicode(code)

            if 'source_file' not in request.files or not code:
                code = request.form['source_code']

            sub = Submission(
                team=team.name,
                problem=problem_id,
                language=request.form['language'],
                file=code,
                submitted=datetime.datetime.now()
            )

            team.last_used_language = request.form['language']

            app.db.session.add(sub)
            app.db.session.flush()
            app.db.session.add(SubmissionQueue(submission_id=sub.id))
            app.db.session.commit()
        else:
            abort(400)

        return redirect(url_for('default.list_submissions'))

    if problem_id not in phase.visible_problems:
        abort(404)

    sub = None
    if sub_id is not None:
        team = get_team()
        sub = Submission.query.filter_by(id=sub_id).first()
        if not sub or sub.team != team.name:
            abort(404)
    return render_template('problem.html', problem=problem, sub=sub)


# @default.route('/problem/<problem_id>/assets/<path:asset>')
@default.route('/problem/<problem_id>/<path:asset>')
def get_problem_asset(problem_id, asset):
    problem = app.contest.problems.get(problem_id)
    phase = app.contest.get_current_phase()
    if not problem or problem_id not in phase.visible_problems:
        abort(404)

    if not problem.assets:
        abort(404)

    return send_from_directory(problem.assets, asset)


@default.route('/login/', methods={'GET', 'POST'})
def login():
    goto = request.args.get('next', url_for('index'))
    registered = request.args.get('register', 'False') == 'True'
    team_name = ''
    bad_login = False
    if is_logged_in():
        return redirect(goto)
    if request.method == 'POST':
        # TODO: make sure 'team' and 'password' are in request.form
        team_name = request.form['team']
        password = request.form['password']
        if team_name in app.contest.teams and app.contest.teams[team_name].password == password:
            session['team'] = team_name
            return redirect(goto)
        else:
            session.pop('team', '')
            bad_login = True
    return render_template('login.html', team_name=team_name, bad_login=bad_login, registered=registered)


@default.route('/logout/')
def logout():
    session.pop('team', '')
    return redirect(url_for('index'))


def _register_team(name, password):
    global opts
    global contest

    with open(os.path.join(app.opts.contest, 'teams.yml'), 'r') as f:
        inp = f.read()

    with open(os.path.join(app.opts.contest, 'teams.yml'), 'w') as f:
        for line in inp.strip().split('\n'):
            f.write(line + '\n')
            if line.strip() == 'teams:':
                f.write('    "%s": {pass: "%s", location: unknown, groups:[all]}\n' % (name, password))

    app.contest = Contest.load(app.opts.contest)


@default.route('/register/', methods={'GET', 'POST'})
def register():
    global contest
    if not app.contest.register or is_logged_in():
        abort(404)

    team_name = ''
    error = []

    if request.method == 'POST':
        # TODO: make sure 'team' and 'password' are in request.form
        team_name = request.form['team']
        password = request.form['password']
        confirm_password = request.form['confirm_password']

        rx = '^[-_A-Za-z0-9 ]{3,20}$'
        if not re.match(rx, team_name):
            error.append('Team name is illegal (it must match %s).' % rx)

        if team_name in app.contest.teams:
            error.append('Team name is already taken.')

        rx = '^[-_A-Za-z0-9 ]{5,20}$'
        if not re.match(rx, password):
            error.append('Password is illegal (it must match %s).' % rx)

        if password != confirm_password:
            error.append('Password confirmation was incorrect.')

        if not error:
            _register_team(team_name, password)
            return redirect(url_for('default.login', register='True'))

    return render_template('register.html', team_name=team_name, error=error)

server/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ contest.title }}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='components/bootstrap/dist/css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='components/fontawesome/css/font-awesome.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='components/codemirror/lib/codemirror.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='components/codemirror/theme/ambiance.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}" />
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
                ignoreClass: ".*",
                inlineMath: [['$','$'], ['\\(','\\)']]
            },
            MMLorHTML: {
                prefer: {Firefox: "HTML"}
            }
        });
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.4.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full" type="text/javascript"></script>
</head>
<body id="epsilon">
{% block body %}{% endblock %}
<script src="{{ url_for('static', filename='components/jquery/dist/jquery.min.js') }}"></script>
<!-- <script src="{{ url_for('static', filename='jquery-ui/jquery-ui.min.js') }}"></script> -->
<script src="{{ url_for('static', filename='components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/lib/codemirror.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/keymap/vim.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/keymap/emacs.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/keymap/sublime.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/clike/clike.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/python/python.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/perl/perl.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/pascal/pascal.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/ruby/ruby.js') }}"></script>
<script src="{{ url_for('static', filename='components/codemirror/mode/javascript/javascript.js') }}"></script>
<script src="{{ url_for('static', filename='js/site.js') }}"></script>
{% block below %}{% endblock %}
</body>
</html>

server/templates/index.html
{% extends "main.html" %}
{% block content %}
    <div class="hero-unit offset2 span7">
        <h1>Hello there{{ ', %s' % team.name if team else '' }}!</h1>
        <p>
            {% if contest.status() == contest.BEFORE_START %}
                {% set hrs = int(1 + contest.time_to_start() / 60 / 60) %}
                You feeling excited yet? The contest starts in less than {{ hrs }} hour{{ '' if hrs == 1 else 's' }}.
                {% if not team %}
                    You have to be logged in to submit your solutions, so you might as well go ahead and <a href="{{ url_for('default.login') }}">log in</a> now.
                {% else %}
                    I can see that you're already logged in. Awesome!
                {% endif %}
                Well, that's all for now. Good luck and may the force be with you!
            {% elif contest.status() == contest.RUNNING %}
                The contest has begun. Woohoo!
                If you haven't already, go ahead and pick a problem from the list to the left.
                {% if not team %}
                    You don't seem to be logged in though, so you won't be able to submit your solutions.
                    Maybe you should go ahead and <a href="{{ url_for('default.login') }}">log in</a> before you pick a problem?
                {% endif %}
                Anyway, we hope you're doing well!
            {% else %}
                The contest has finished. That was awesome!
                You can take take a look at the final standings in the <a href="{{ url_for('default.view_scoreboard') }}">scoreboard</a>, or pick a problem from the list to the left and try for yourself.
                We hope you enjoyed the contest!
            {% endif %}
        </p>
    </div>
{% endblock %}

server/templates/login.html
{% extends "main.html" %}
{% block content %}

<form class="form-horizontal form-signin" action="" method="post">
    <fieldset>
        <div id="legend">
            <legend class="">Log in</legend>
        </div>

        {% if registered %}
            <div class="alert alert-success">
                <h4>Registration successful!</h4>
                Welcome! Go ahead and log in.
            </div>
        {% endif %}

        {% if bad_login %}
            <div class="alert alert-danger">
                <h4>Bad credentials!</h4>
                Make sure you typed in the correct password.
            </div>
        {% endif %}

        <div class="form-group">
            <label class="control-label" for="team">Team name</label>
            <input type="text" id="team" name="team" value="{{ team_name }}" class="input-xlarge form-control">
        </div>

        <div class="form-group">
            <label class="control-label" for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="" class="input-xlarge form-control">
        </div>

        <div class="form-group">
            <button class="btn btn-success">Log in</button>
        </div>
    </fieldset>
</form>

{% endblock %}

server/templates/main.html
{% extends "base.html" %}
{% block body %}

<div class="navbar navbar-default navbar-fixed-top header">
    <div class="navbar-inner">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <button type="button" class="navbar-toggle pull-left collapsed sidebar-toggle">
                    <span class="sr-only">Toggle sidebar</span>
                    <i class="fa fa-arrow-left"></i>
                </button>
                <a class="navbar-brand" href="{{ url_for('index') }}">{{ contest.title }}</a>
                {% if phase.status %}
                    <p class="navbar-text">{{ phase.status }}</p>
                {% endif %}
                {% if phase.countdown != None and phase.current_countdown() >= 0 %}
                    <p class="navbar-text countdown">{{ phase.current_countdown() | format_time }}</p>
                {% endif %}
            </div>
            <div class="collapse navbar-collapse" id="topbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if team: %}
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ team.name }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('default.logout') }}"><i class="fa fa-user-times"></i> Log out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('default.login') }}"><i class="fa fa-user"></i> Log in</a></li>
                        {% if contest.register %}
                            <li><a href="{{ url_for('default.register') }}"><i class="fa fa-plus"></i> Register</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="wrapper">
    <div class="sidebar-wrapper">
        <ul class="nav sidebar nav-stacked problem-list">
            {% if phase.scoreboard_problems %}
                <li><a href="{{ url_for('default.view_scoreboard') }}"><i class="fa fa-flag"></i> Scoreboard</a></li>
            {% endif %}
            {% if team %}
                <li><a href="{{ url_for('default.list_submissions') }}"><i class="fa fa-check-square-o"></i> Submissions</a></i>
            {% endif %}
            <!-- <li class="nav-header">Problems</li> -->
            {% if phase.problem_list %}
                {% set ns = namespace(cnt=1) %}
                {% for k, v in phase.problem_list %}
                    {% if k == 'header' %}
                        <li class="nav-header" style="font-size: 0.7em; margin-top: 0; margin-bottom: -6px;">{{ v }}</li>
                    {% elif k == 'text' %}
                        <li class="nav-header">{{ v }}</li>
                    {% elif k == 'problem' %}

                        <li class="problem {% if problem and problem.id == v %}active{% endif %} {% if v in solved %}ac{% elif v in tried %}wa{% endif %}">
                            <a href="{{ url_for('default.view_problem', problem_id=v) }}" class="{% if problem and problem.id == v %}active{% endif %}"><span class="number">{{ ns.cnt }}.</span> {{ contest.problems[v].title | safe }}</a>
                        </li>

                        {% set ns.cnt = ns.cnt + 1 %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <li>No problems available</li>
            {% endif %}
        </ul>
    </div>
    <div class="content-wrapper">
        <div class="container-fluid" id="main">
            <div class="row">
                <div class="col-xs-12 content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 footer">
            <hr />
            generated in {{ "%.04f" % (g.request_time() * 1000.0) }}ms by <span class="epsilon" title="epsilon">&epsilon;</span>
        </div>
    </div>

</div>
{% endblock %}

server/templates/register.html
{% extends "main.html" %}
{% block content %}

<form class="form-horizontal form-signin" action="" method="post">
    <fieldset>
        <div id="legend">
            <legend class="">Register</legend>
        </div>

        {% if error %}
            <div class="alert alert-danger">
                <h4>Registration unsuccessful!</h4>
                <ul>
                    {% for e in error %}
                        <li>{{ e }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="form-group">
            <label class="control-label" for="team">Team name</label>
            <input type="text" id="team" name="team" value="{{ team_name }}" class="input-xlarge form-control">
        </div>

        <div class="form-group">
            <label class="control-label" for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="" class="input-xlarge form-control">
        </div>

        <div class="form-group">
            <label class="control-label" for="confirm_password">Confirm password</label>
            <input type="password" id="confirm_password" name="confirm_password" placeholder="" class="input-xlarge form-control">
        </div>

        <div class="form-group">
            <button class="btn btn-success">Register</button>
        </div>
    </fieldset>
</form>

{% endblock %}

server/templates/scoreboard.html
{% extends "main.html" %}
{% block title %}
{{ contest.title }} - scoreboard
{% endblock %}
{% block content %}

{% if phase.frozen != None and contest.time_elapsed() >= 60.0 * phase.frozen %}
    <h4>The scoreboard has been frozen</h4>
{% endif %}

<div class="btn-group" style="margin-bottom:10px">
    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Groups
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        {% for title, group in sorted(map(reversed, contest.groups.items())) %}
            <li><a href="{{ url_for('default.view_scoreboard', opts='groups=' + group) }}">{{ title }}</a></li>
        {% endfor %}
    </ul>
</div>

<table class="table table-bordered table-striped scoreboard">
    <tr>
        <th>#</th>
        <th>Team</th>
        <th>Points</th>
        <th>Penalty</th>
        {% for i, problem in enumerate(phase.scoreboard_problems) %}
            {# <th>{{ contest.problems[problem].title }}</th> #}
            <th title="{{ contest.problems[problem].title }}">{{ i+1 }}</th>
        {% endfor %}
    </tr>
    {% for i, (team, points, penalty, sb) in enumerate(scoreboard) %}
        <tr>
            <td>
                {% if points > 0 %}
                    {{ i+1 }}
                {% endif %}
            </td>
            <td>{{ contest.teams[team].title }}</td>
            <td>{{ points }}</td>
            <td>{{ penalty | format_time }}</td>
            {% for p in phase.scoreboard_problems %}
                {% set problem = sb[p] %}

                {% if problem.solved_at != None %}
                    <td class="ac">
                {% elif problem.new_submissions > 0 %}
                    <td class="new">
                {% elif problem.try_count > 0 %}
                    <td class="wa">
                {% else %}
                    <td>
                {% endif %}

                    {% if problem.solved_at == None %}
                       --:--
                    {% else %}
                        {{ problem.solved_at | format_time }}
                    {% endif %}

                    {% if problem.try_count > 0 or problem.new_submissions > 0 %}
                    ({{ problem.try_count }}{% if problem.new_submissions > 0 %}+{{ problem.new_submissions }}{% endif %})
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

{% endblock %}

server/templates/scoreboard_full.html
{% extends "base.html" %}
{% block title %}
{{ contest.title }} - scoreboard
{% endblock %}
{% block body %}

<div class="content">

    {% if phase.frozen != None and contest.time_elapsed() >= 60.0 * phase.frozen %}
        <h4>The scoreboard has been frozen</h4>
    {% endif %}

    <table class="table table-bordered table-striped scoreboard">
        <tr>
            <th>#</th>
            <th>Team</th>
            <th>Points</th>
            <th>Penalty</th>
            {% for i, problem in enumerate(phase.scoreboard_problems) %}
                {# <th>{{ contest.problems[problem].title }}</th> #}
                <th title="{{ contest.problems[problem].title }}">{{ i+1 }}</th>
            {% endfor %}
        </tr>
        {% for i, (team, points, penalty, sb) in enumerate(scoreboard) %}
            <tr>
                <td>
                    {% if points > 0 %}
                        {{ i+1 }}
                    {% endif %}
                </td>
                <td>{{ contest.teams[team].title }}</td>
                <td>{{ points }}</td>
                <td>{{ penalty | format_time }}</td>
                {% for p in phase.scoreboard_problems %}
                    {% set problem = sb[p] %}

                    {% if problem.solved_at != None %}
                        <td class="ac">
                    {% elif problem.new_submissions > 0 %}
                        <td class="new">
                    {% elif problem.try_count > 0 %}
                        <td class="wa">
                    {% else %}
                        <td>
                    {% endif %}

                        {% if problem.solved_at == None %}
                        --:--
                        {% else %}
                            {{ problem.solved_at | format_time }}
                        {% endif %}

                        {% if problem.try_count > 0 or problem.new_submissions > 0 %}
                        ({{ problem.try_count }}{% if problem.new_submissions > 0 %}+{{ problem.new_submissions }}{% endif %})
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>

</div>

{% endblock %}

{% block below %}
<script type="text/javascript">
    jQuery(function ($) {
        var timeout = 10000;
        var refresh_body = function () {
            $('.content').load(window.location + " .content", function () {
                setTimeout(refresh_body, timeout);
            });
        };

        setTimeout(refresh_body, timeout);
    });
</script>
{% endblock %}

server/templates/submission.html
{% extends "main.html" %}
{% block title %}
{{ contest.title }} - submission {{ submission.id }}
{% endblock %}
{% block content %}
    <h3>Details for submission {{ submission.id }}</h3>
    <h5>Team {{ submission.team }}, problem {{ contest.problems[submission.problem].title | safe }}, submitted at {{ submission.submitted | format_time }}</h5>
    {# <pre><code>{{ submission.file }}</code></pre> #}
    <textarea id="source_code">{{ submission.file }}</textarea>
    <div class="form-group">
        <h4>Actions:</h4>
        <a href="{{url_for('default.view_problem', problem_id=submission.problem)}}" class="btn btn-primary"><i class="fa fa-eye"></i> View Problem</a>
        <a href="{{url_for('default.view_problem', problem_id=submission.problem, sub_id=submission.id)}}" class="btn btn-warning"><i class="fa fa-edit"></i> Edit</a>
    </div>
    <hr />
    <h4>Verdict: {{ submission.verdict }}</h4>
    <hr />
    {% if submission.judge_response != None %}
        {{ submission.judge_response | safe }}
    {% endif %}
{% endblock %}
{% block below %}
<style type="text/css">
    .CodeMirror {
        height: auto;
        overflow-x: auto;
        overflow-y: hidden;
    }
</style>
<script type="text/javascript">

    jQuery(function ($) {

        CodeMirror.fromTextArea($('#source_code')[0], {
            'mode': '{{ contest.languages[submission.language].highlight }}',
            'theme': 'ambiance',
            'readOnly': true,
            'lineNumbers': true
        });

    });

</script>
{% endblock %}

server/templates/submissions.html
{% extends "main.html" %}
{% block title %}
{{ contest.title }} - submissions
{% endblock %}
{% block content %}
    <table class="table table-condensed submissions">
        <tr>
            <th class="sub_id">ID</th>
            <th class="sub_submitted">Submitted</th>
            <th class="sub_team">Team</th>
            <th class="sub_problem">Problem</th>
            <th class="sub_language">Language</th>
            <th class="sub_verdict">Verdict</th>
            <th class="sub_time">Time</th>
            <th class="sub_memory">Memory</th>
        </tr>
        {% for sub in submissions %}
            <tr class="row-success {{ format_verdict_classes(sub.verdict) }}">
                <td class="sub_id"><a href="{{ url_for('default.view_submission', sub_id=sub.id) }}">{{ sub.id }}</a></td>
                <td class="sub_submitted">{{ sub.submitted | format_time }}</td>
                <td class="sub_team">{{ sub.team }}</td>
                <td class="sub_problem"><a href="{{ url_for('default.view_problem', problem_id=sub.problem) }}">{{ contest.problems[sub.problem].title | safe }}</a></td>
                <td class="sub_language">{{ sub.language }}</td>
                <td class="sub_verdict">
                    {% for verdict in sub.verdict.split('+') %}
                        <span class="{{ label_class_for(verdict) }}" title="{{ verdict_explanation.get(verdict, verdict) }}">{{ verdict }}</span>
                    {% endfor %}
                </td>
                <td class="sub_time">{{ '' if sub.time == None else '%d ms' % sub.time }}</td>
                <td class="sub_memory">{{ '' if sub.memory == None else '%d KB' % sub.memory }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}